name: lede
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      config:
        description: '请输入配置文件名称'
        required: true
        default: 'xiaomi-mini-print.config'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 环境检查
      uses: actions/checkout@master
    - name: 下载安装编译所需套件
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        git clone https://github.com/coolsnowwolf/lede
        cd lede
    - name: 定制固件
      run: |
        chmod +x ./diy.sh && ./diy.sh
    - name: 开始编译固件
      working-directory: ./lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a   
        make defconfig
        echo -e "$(nproc) thread build."
        make download -j$(nproc)
        make -j$(nproc) V=s
        echo -e "编译完成!"
    - name : 上传固件
      uses: actions/upload-artifact@master
      with:
        name: lede
        path: lede/bin
