name: diy
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      config:
        description: '请输入配置文件名称'
        required: true
        default: 'xiaomi-mini-print.config'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 环境检查
      uses: actions/checkout@master
    - name: 下载安装编译所需套件
      run: |
        sudo apt-get update
        sudo apt-get full-upgrade -y
        sudo apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev python3-setuptools
        git clone https://github.com/coolsnowwolf/lede
        cd lede
    - name: 定制固件
      env:
        CONFIG_FILE: "${{ github.event.inputs.config }}"
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
        chmod +x ./diy.sh && ./diy.sh
    - name: 开始编译固件
      working-directory: ./lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a   
        make defconfig
        echo -e "单线程编译"
        make download -j1
        make -j1 V=s
        echo -e "编译完成!"
    - name : 上传固件
      uses: actions/upload-artifact@master
      with:
        name: lede
        path: lede/bin
